# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-19 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20181019_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
