# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-14 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20181019_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='industry',
        ),
    ]
