# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-18 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(default='http//:google.com', max_length=254),
        ),
    ]
