# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-18 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(default='http://google.com', max_length=254),
        ),
    ]
