# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-18 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20181018_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.CharField(default='http://google.com', max_length=254),
        ),
    ]
